name: Deploy to VPS

on:
  push:
    branches:
      - main # atau sesuaikan dengan branch yang ingin di-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env' \
            --exclude='.github' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

      - name: Change Directory
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com"

      - name: Install Dependencies
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST 'bash -l -c "cd /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com && bun install"'

      - name: Start PM2
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "source ~/.bashrc && cd /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com && /usr/local/lib/node_modules/pm2/bin/pm2 start ecosystem.config.cjs --env production --update-env && /usr/local/lib/node_modules/pm2/bin/pm2 save"
