name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$ENV_FILE" > .env
          cat .env

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: /home/api-check-carabaopro/htdocs/api-check.carabaopro.com
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.github' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

      - name: Setup and Start Application
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
            cd /home/api-check-carabaopro/htdocs/api-check.carabaopro.com && \
            source ~/.bashrc && \
            bun install && \
            /usr/local/lib/node_modules/pm2/bin/pm2 delete carabao-product-management-api || true && \
            /usr/local/lib/node_modules/pm2/bin/pm2 start ecosystem.config.cjs --env production && \
            /usr/local/lib/node_modules/pm2/bin/pm2 save
          "
