name: Deploy to VPS

on:
  push:
    branches:
      - main # atau sesuaikan dengan branch yang ingin di-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env' \
            --exclude='.github' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

      - name: Execute Remote Commands
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "\
            cd /home/carabaopro-api-check-ssh/htdocs/api-check.carabaopro.com && \
            bun install && \
            npm install pm2 --save-dev && \
            ./node_modules/.bin/pm2 start ecosystem.config.js --update-env && \
            ./node_modules/.bin/pm2 save"
